-- Supabase SQL: Projects table and permissive development RLS policies
-- Execute this script in Supabase SQL Editor (SQL -> New query) and Run.

-- 1) Ensure pgcrypto for gen_random_uuid()
create extension if not exists pgcrypto;

-- 2) Drop old projects table if it exists to apply the new schema
--    Note: This will remove any existing data. Back up before running in production.
drop table if exists public.projects;

-- 3) Create projects table with required columns:
--    - id: UUID primary key, generated by gen_random_uuid()
--    - name: varchar(120), required
--    - project_key: varchar(20), required and UNIQUE (suitable for short codes like "BUG" or "APP")
--    - description: text, optional
--    - created_at: timestamptz, default now(), required
--    - colour: varchar(30), optional (store CSS color names or hex codes like "#FFAA00")
create table public.projects (
  id uuid primary key default gen_random_uuid(),
  name varchar(120) not null,
  project_key varchar(20) not null unique,
  description text,
  created_at timestamp with time zone not null default now(),
  colour varchar(30)
);

-- 4) Enable Row Level Security (RLS)
alter table public.projects enable row level security;

-- 5) Development RLS policies (permissive). Adjust for production as needed.
--    Drop existing policies first to avoid duplicates on re-runs.
drop policy if exists "Allow select for all (dev)" on public.projects;
drop policy if exists "Allow insert for all (dev)" on public.projects;

-- Re-create permissive policies for development/testing
create policy "Allow select for all (dev)"
  on public.projects
  for select
  using (true);

create policy "Allow insert for all (dev)"
  on public.projects
  for insert
  with check (true);

-- Optional: verification queries
-- select table_name from information_schema.tables where table_schema='public' and table_name='projects';
-- select column_name, data_type, is_nullable from information_schema.columns where table_schema='public' and table_name='projects' order by ordinal_position;
